### ISSUE TITLE
No option to backspace

### ISSUE THREAD

**Issue by RivanParmar** [HuyHung1408/Fluent-Python-Calculator#10]
There is no option to backspace. You can't remove single digits in the entry widget. There is option to only clear the widget and you have to type everything back again.

Possible solution:
- Add another button for backspace.
OR
- Make it such that on clicking the "C" button once, removes a single digit from the entry widget and on long press, clears the entire widget.

**Comment by HuyHung1408** [comment]
Will try to add this, thanks!

**Comment by HuyHung1408** [comment]
Where would you want to put the button?

**Comment by RivanParmar** [comment]
Maybe near the entry widget? That is, on it's right side.

**Comment by HuyHung1408** [comment]
@RivanParmar How do you think if I remove the 'M' button to darkdetect to free up space for the backspace button?

**Comment by RivanParmar** [comment]
Yes, it would be great to do something like that, however place the backspace button on the right side and not the left as it would look good as well as be easier to click.

**Comment by HuyHung1408** [comment]
Ok, thank you!

**Comment by HuyHung1408** [comment]
https://user-images.githubusercontent.com/86362423/156884893-87e059f9-e80d-4005-a42e-ffd1f6c9ed68.mp4

Works like a charm! Thanks for giving me suggestion! @RivanParmar

**Comment by RivanParmar** [comment]
> 
> https://user-images.githubusercontent.com/86362423/156884893-87e059f9-e80d-4005-a42e-ffd1f6c9ed68.mp4
> 
> Works like a charm! Thanks for giving me suggestion! @RivanParmar 

Yes, it is looking awesome!

**Comment by HuyHung1408** [comment]
Coming soon with beta 6 or maybe version 1!
