### ISSUE TITLE
App's UI is not working perfectly

### ISSUE THREAD

**Issue by RivanParmar** [HuyHung1408/Fluent-Python-Calculator#12]
I downloaded the v5 (Beta) version and ran it on my Windows 10 laptop and here's how it looks:

![Fluent Calculator 2_19_2022 7_44_59 PM](https://user-images.githubusercontent.com/77159650/154804646-98f5805b-c135-485e-8a30-7ecde7ad7e16.png)
![Fluent Calculator 2_19_2022 7_45_10 PM](https://user-images.githubusercontent.com/77159650/154804648-b6d34d63-debe-4422-b1fa-cc5a0c6a68d2.png)
![Fluent Calculator 2_19_2022 7_45_16 PM](https://user-images.githubusercontent.com/77159650/154804649-845f6521-303c-4ddb-b44f-597d437a13a1.png)

The first photo's background is white only, however on taking screenshot, it shows black. The second photo is of dark mode. The third photo is after disabling dark mode, in which also the background is white but in screenshot it is black.
I am running Windows 10 Version 21H1.

**Comment by HuyHung1408** [comment]
Can you try v4 one? I think it's the blurwinows issue, does the acrylic effects works?

**Comment by RivanParmar** [comment]
Yes, the UI is working perfectly in v4.

**Comment by HuyHung1408** [comment]
Thanks for the information, what screenshot program did you use?

**Comment by RivanParmar** [comment]
I am using Windows' own program, i.e., Xbox Game Bar to capture the screenshots.

**Comment by HuyHung1408** [comment]
Ok, thank you. I just tested, it only have a black background when capturing the app, in normal condition it's still good.  I think this occurs because the app's background was transparent and blurwindow draw an Acrylic as the background of the app. Thanks for your information!

**Comment by HuyHung1408** [comment]
> By the way, do you want to use Mica effect in the app or the Acrylic effect? Also should I suggest reverting back to how the original theming worked without importing the sv_ttk theme? As it used to work great. However, now, there are white spaces left around the corners of the buttons as you can see in the 1st and 2nd photo that I had posted earlier.

Yes, I planned to revert back to the old one because the new method can't change to .exe file. The square corners should be fixed in up coming version! Thanks a lot!

**Comment by HuyHung1408** [comment]
New:
![image](https://user-images.githubusercontent.com/86362423/155639465-32c628d6-4718-479d-876b-136ec01448f0.png)
 
Old:
![image](https://user-images.githubusercontent.com/86362423/155639622-fc4684a0-f70c-4fa3-8770-26df7ac6c8d4.png)

**Comment by RivanParmar** [comment]
> > By the way, do you want to use Mica effect in the app or the Acrylic effect? Also should I suggest reverting back to how the original theming worked without importing the sv_ttk theme? As it used to work great. However, now, there are white spaces left around the corners of the buttons as you can see in the 1st and 2nd photo that I had posted earlier.
> 
> Yes, I planned to revert back to the old one because the new method can't change to .exe file. The square corners should be fixed in up coming version! May be I will keep the Acrylic as the default one (because Windows 10 doesn't support Mica). Thanks a lot! 

Ok. You're welcome!

**Comment by HuyHung1408** [comment]
using png instead of gif make the button slow or not respond. But use gif make the program looks like your first screenshot. This is the biggest issue that stop me from develop new features. Do you have any idea about it?

**Comment by HuyHung1408** [comment]
Yeah, you're right. Not sure if I can do anything to solve this, kinda annoying

https://user-images.githubusercontent.com/86362423/155833194-195b0223-fca9-48c0-a15c-7b8bc4723032.mp4

**Comment by RivanParmar** [comment]
So what should we do now about the Acrylic effect? Does it work perfectly in Windows 11? If yes, then we could remove that effect if the app is run on Windows 10 so that it's layout would be just as before. And if we do that, then instead of Acrylic effect we might use Mica effect. Or if you still want to have Acrylic effect on Windows 10, then I have found an answer to such a question on StackOverflow, however I haven't checked if it works. Here's the link to the answer: https://stackoverflow.com/a/70379149

**Comment by HuyHung1408** [comment]
Acrylic works good in Windows 11 and I agree with you that we should use Mica effects in Windows 11 as it match Windows 11 more!

**Comment by RivanParmar** [comment]
And what about Acrylic effect on Windows 10? Should we try and add it as shown in the answer or should we just remove it completely?

**Comment by HuyHung1408** [comment]
> And what about Acrylic effect on Windows 10? Should we try and add it as shown in the answer or should we just remove it completely?

I will not remove it, I'm thinking about making a different version for it, like one file is for Windows 11, another is for Windows 10. Btw I think why the button needs to click multiple times to make them responsive and it's only happens in light mode because the buttons on light mode when clicked is transparent while dark is not!

**Comment by HuyHung1408** [comment]
How do you think if I remove the 'M' button to darkdetect to free up space for the backspace button?

**Comment by RivanParmar** [comment]
There is no need to create a different file for Windows 10 and 11, you can simply just check the system's version and only add Acrylic or Mica if it is Windows 11. While on Windows 10, let the background remain as in v4 and only add rounded corners around the window which would look good. To add rounded corners to window here is something that I have found and will try to implement: https://stackoverflow.com/a/68890935/15545774 And to check the Windows version, here is another answer: https://stackoverflow.com/a/66554956/15545774

**Comment by HuyHung1408** [comment]
Will check that too, thanks!

**Comment by HuyHung1408** [comment]
@RivanParmar can you check if the icon in backspace button shows up?

**Comment by RivanParmar** [comment]
The icon in the backspace is showing perfectly. I have also tried implementing rounded corners to the window, however there isn't any effect of it on the window. I am creating a pull request with some image edits again and I have commented out the BlurWindow codes for Windows 10 as it isn't working properly and isn't looking good. Moreover, I am also upgrading to Windows 11 in some time and so I won't be able to see the UI on Windows 10.

**Comment by HuyHung1408** [comment]
Ah, thanks a lot for your efforts

**Comment by HuyHung1408** [comment]
Version 1 may be coming in a few hours or a few days!

**Comment by RivanParmar** [comment]
> Version 1 may be coming in a few hours or a few days!

That's a great news!

**Comment by RivanParmar** [comment]
Here's how it's looking on Windows 10 :
In light mode:
![Fluent Calculator 3_7_2022 9_49_55 PM.png](https://user-images.githubusercontent.com/77159650/157075151-84f158f0-faa8-4f24-a835-db89c8cfafac.png)

In dark mode:
![Fluent Calculator 3_7_2022 9_50_35 PM.png](https://user-images.githubusercontent.com/77159650/157075178-92e8fa1a-9c28-4266-8b5c-5ca3a5b0f5ed.png)

And one more note, the themes aren't changing when I change Windows 10's theme to dark when the application is running. The dark mode change occurs only when I close the app and reopen it again.

**Comment by RivanParmar** [comment]
Have upgraded to Windows 11 and the app's looking awesome on it! You can close this issue now.
