### ISSUE TITLE
Cannot import sv_ttk

### ISSUE THREAD

**Issue by RivanParmar** [HuyHung1408/Fluent-Python-Calculator#13]
This isn't exactly an issue but, on opening the source code files in VSCode, it shows error on 'import sv_ttk'. The error is `ModuleNotFoundError: No module named 'sv_ttk'`. I have also downloaded this repository: [https://github.com/rdbende/Sun-Valley-ttk-theme](url), however it isn't working. Moreover I could not find any other library named sv_ttk. I have the BlurWindow module and there's no error in importing it. So, could you please describe the steps to setup sv-ttk in VSCode project?

**Comment by HuyHung1408** [comment]
https://github.com/rdbende/Sun-Valley-ttk-theme/discussions/19 here just install the package like normal.

**Comment by RivanParmar** [comment]
Thanks for the information!

**Comment by HuyHung1408** [comment]
No problems!
