### ISSUE TITLE
Better way of using Mica with tkinter

### ISSUE THREAD

**Issue by Olikonsti** [HuyHung1408/Fluent-Python-Calculator#15]
Hey, I found a way of using mica with tkinter without a third party app

You need to use these two pieces of code

https://gist.github.com/Olikonsti/879edbf69b801d8519bf25e804cec0aa
the first one enables the windows immersive dark mode with a dark title bar

https://gist.github.com/Olikonsti/8cbcba376c92831a27bc92ce0bb4dbc7
this code blurs the window

you first run dark_title_bar(window) on your window
and then enable_blur(window)

this needs to happen after changing window.resizable()

I am currently building a library with the sun valley ttk theme, the tkinter blur and extra widgets like scrollframes and entry boxes with ghost text: https://github.com/Olikonsti/MTK

**Comment by HuyHung1408** [comment]
Thanks a lot! I will look into this

**Comment by sumeshir26** [comment]
@HuyHung1408 You could also use [win32mica](https://github.com/martinet101/win32mica) which also makes the titlebar mica. I implemented it in TimerX like this: https://github.com/Futura-Py/TimerX/pull/94/files

**Comment by HuyHung1408** [comment]
> @HuyHung1408 You could also use [win32mica](https://github.com/martinet101/win32mica) which also makes the titlebar mica. I implemented it in TimerX like this: https://github.com/Futura-Py/TimerX/pull/94/files

Thanks, I will add if I have free time. I'm too busy at this time

**Comment by HuyHung1408** [comment]
> @HuyHung1408 You could also use [win32mica](https://github.com/martinet101/win32mica) which also makes the titlebar mica. I implemented it in TimerX like this: https://github.com/Futura-Py/TimerX/pull/94/files

![image](https://user-images.githubusercontent.com/86362423/156877339-04b54a46-98ab-4a69-bb96-6835846804df.png)
Something is wrong here

**Comment by sumeshir26** [comment]
Make sure to remove the `import BlurWindow` line since BlurWindw causes tha issue

**Comment by HuyHung1408** [comment]
> Make sure to remove the `import BlurWindow` line since BlurWindw causes tha issue
ahhh, thanks a lot lol.

**Comment by HuyHung1408** [comment]
Thanks y'all !

**Comment by sumeshir26** [comment]
well, you forgot to update requirements.txt so u mght want to change that

**Comment by HuyHung1408** [comment]
> well, you forgot to update requirements.txt so u mght want to change that

ah thanks

**Comment by sumeshir26** [comment]
also, you should add darkdetect to requiremtst.txt
