### ISSUE TITLE
Make titlebar dark

### ISSUE THREAD

**Issue by not-nef** [HuyHung1408/Fluent-Python-Calculator#5]
In the latest release notes you said that you look for a way to make the Titlebar change color. I dont know a direct solution, but when using the `BlurWindow` Module (`python -m pip install BlurWindow`) with `Dark = True`, the titlebar changes its color to dark. And the window also gets blurred, which looks great on modern apps! I would make a pull request, but i cant get to my PC at the moment.

EDIT: i dont know if this solution also works for the menu bar. You need to check.

**Comment by HuyHung1408** [comment]
Thank you a lot! I saw your beautiful project and I'm finding a way to contact you. But now it's unnecessary. Will try after holiday end.

**Comment by HuyHung1408** [comment]
I'm not sure how to apply blur to my program after installed BlurWindow, just started to learn about Python 4 days ago.

**Comment by not-nef** [comment]
Its easy, just add the following lines to your code:
```
bg_color = ttk.Style().lookup(".", "background")
app.wm_attributes("-transparent", bg_color)
app.update()
HWND = ctypes.windll.user32.GetForegroundWindow()
GlobalBlur(HWND)
```

**Comment by not-nef** [comment]
Keep in mind that you have to replace `app` with the name of your tkinter window.

**Comment by im-coder-lg** [comment]
Hi, I just want to know if you created this project by learning through YouTube. Coincidentally, I also made a program that mimics the entire code, except the theming. Just wanna know, and it's great seeing @not-nef too.

**Comment by im-coder-lg** [comment]
You can use the code, anyway I put my edition in the public domain, but I just want to know, since the code is like an exact copy, except your abridged features.

**Comment by im-coder-lg** [comment]
Wait, you said [here](https://github.com/HuyHung1408/Fluent-Python-Calculator/issues/5#issuecomment-1025287215) that you saw our beautiful project, are you talking about TimerX? That's the only one I know, just a doubt. If you do like it, feel free to contribute too! We are looking for more features to add, especially since we hit the stable mark.

**Comment by im-coder-lg** [comment]
Also, @not-nef this works only on Windows, since there are a bunch of errors when you try getting it onto POSIX-compliant operating systems like macOS and Linux.

**Comment by HuyHung1408** [comment]
> Hi, I just want to know if you created this project by learning through YouTube. Coincidentally, I also made a program that mimics the entire code, except the theming. Just wanna know, and it's great seeing @not-nef too.

yeah, I did lol, my teacher just taught me some basic things of python, else, I just search the internet

**Comment by im-coder-lg** [comment]
Oh, then it's fine. You can carry on. I still have to update my code base lol.

**Comment by HuyHung1408** [comment]
> 

I will do if I learn more things in the future, my knowledge currently is still very basic!

**Comment by HuyHung1408** [comment]
> Its easy, just add the following lines to your code:
> 
> ```
> bg_color = ttk.Style().lookup(".", "background")
> app.wm_attributes("-transparent", bg_color)
> app.update()
> HWND = ctypes.windll.user32.GetForegroundWindow()
> GlobalBlur(HWND)
> ```

Thanks a lot!

**Comment by im-coder-lg** [comment]
Also, that code works only on Windows. You need to import BLurWindow too. You can take an example of the implementation from TimerX.

**Comment by HuyHung1408** [comment]
Ok, my calculator was transparent, what should I do next? (Sorry if this is a stupid question). This is the first time I do something much complex like this one.

**Comment by not-nef** [comment]
> Ok, my calculator was transparent, what should I do next? (Sorry if this is a stupid question). This is the first time I do something much complex like this one.

I forgot to tell you, you have to import ctypes at the beginning of your code!

**Comment by HuyHung1408** [comment]
I've added it after seeing it missing, still transparent. Thanks for your help. Guess I will try after holiday week. My parent told me to shut down the computer. See you later.

**Comment by not-nef** [comment]
Bye

**Comment by not-nef** [comment]
did you import the BlurWindow module correctly? You have to do `from BlurWindow.blurwindow import *`

**Comment by im-coder-lg** [comment]
I told @HuyHung1408 to implement it from TimerX. We did it better, hence I asked him to refer to our project.

**Comment by HuyHung1408** [comment]
> 

Ok, trying now XD

**Comment by HuyHung1408** [comment]
> did you import the BlurWindow module correctly? You have to do `from BlurWindow.blurwindow import *`

Yes, here is what happening
![image](https://user-images.githubusercontent.com/86362423/151818762-44e350e9-e9e8-48f1-8e08-8f24c27c3d09.png)
![image](https://user-images.githubusercontent.com/86362423/151818738-68f30d4a-2ffd-4183-bdf5-dd27e5337c04.png)

**Comment by im-coder-lg** [comment]
I think that is how it is supposed to be... Did you import ctypes?

**Comment by HuyHung1408** [comment]
>I think that is how it is supposed to be... Did you import ctypes?

yes, after the `from BlurWindow.blurwindow import *`

**Comment by im-coder-lg** [comment]
I meant not supposed to be, sorry for that. @not-nef can you tell how you added blur to TimerX? The TimerX system theme issue with transparency is here, although it's only transparency. How'd you do that?

**Comment by im-coder-lg** [comment]
Oh... I experimented with that. For got about it. Let it be. I will try making a PR to fix this tomorrow, can't boot my PC atm.

**Comment by HuyHung1408** [comment]
> Oh... I experimented with that. For got about it. Let it be. I will try making a PR to fix this tomorrow, can't boot my PC atm.

Ok, thank you a lot

**Comment by HuyHung1408** [comment]
> Also, I can't promise when I will make the PR, it's heavy IRL here. So, it is a big if, but if I get the chance, I'll utilise it.

That's ok, don't worry. We can try another method if it didn't work

**Comment by HuyHung1408** [comment]
Thanks a lot, guys, I got it working after reviewing TimerX python files, light mode is cursed haha
![image](https://user-images.githubusercontent.com/86362423/153150965-9d793de2-9e20-4c91-9e3c-0ba9b6433148.png)
![image](https://user-images.githubusercontent.com/86362423/153151088-506514df-4653-451a-983e-f32d27e51205.png)

**Comment by HuyHung1408** [comment]
I think I'll use the button instead of the command bar button for the dark/mode switcher since making the command bar dark will be more complicated. I guess I will focus on the dark/light mode switcher then will add blur and dark title bar later

**Comment by HuyHung1408** [comment]
Thanks a lot!

**Comment by HuyHung1408** [comment]
I pushed my latest changes to Github, there or some issues like Acrylic works with dark mode on start, click 'M' to change dark to light mode then it changes to Acrylic with a light mode, change it again and Acrylic didn't work with dark mode. Not sure why.

**Comment by HuyHung1408** [comment]
Current progress! How to set the titlebar to white again after apply light theme?
![image](https://user-images.githubusercontent.com/86362423/153405998-792975ef-3d56-4bc5-b549-9c67d62aaca4.png)
![image](https://user-images.githubusercontent.com/86362423/153406091-3273aed0-5e0b-46ab-a4aa-7411071f645d.png)

**Comment by sumeshir26** [comment]
Call `GlobalBlur` again, and this time set `Dark` to `False`

**Comment by HuyHung1408** [comment]
> Call `GlobalBlur` again, and this time set `Dark` to `False`

![image](https://user-images.githubusercontent.com/86362423/153407520-1c100dcc-d8a6-410a-9955-44a1a73325ca.png)
Like this, right?

**Comment by im-coder-lg** [comment]
Lookin' great! Hiya @sumeshir26!

**Comment by sumeshir26** [comment]
Yep, like that

**Comment by HuyHung1408** [comment]
Thank all of you!
